// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyajddihoghznxsuolbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5YWpkZGlob2doem54c3VvbGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjI0NDIsImV4cCI6MjA2MDM5ODQ0Mn0.XGv_T5pHUA2uN3FkJzbZJ8ipjrexBtDQoeR-WfN3_hI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);